application: gcdc2013-pinpoint
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:

- url: /styles
  static_dir: styles

- url: /help
  static_dir: help

- url: /.*
  script: main.application